// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IPAddress struct {
	ID           string `json:"id"`
	Response     string `json:"response"`
	IPAddress    string `json:"ip_address"`
	ResponseCode string `json:"response_code"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type Status struct {
	IP      string `json:"ip"`
	Message string `json:"message"`
}
